stages:
  - build
  - deploy

build-job:
  stage: build
  image: docker:24.0
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - main

deploy-job:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client docker-compose
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - scp -o StrictHostKeyChecking=no docker-compose.yml $SSH_USER@$SERVER_IP:/app/
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "cd /app && docker-compose pull && docker-compose up -d"
  only:
    - main