stages:
  - pre-check
  - deploy

mr-dummy:
  stage: pre-check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "Dummy job for merge request checks"
    
deploy_to_vm-job:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to VM..."
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "cd /home/wehavetwochairs/Repositories/Cocktaility && ./deploy.sh"
