version: "3.9"
services:
  postgres:
    container_name: postgres_container_to_cocktaility
    image: postgres:17.2
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_DB: "CockDB"
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru-RU"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user) -d CockDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  pgadmin:
    container_name: pgadmin_container_to_cocktaility
    image: dpage/pgadmin4:8.13
    secrets:
      - pgadmin_password
    environment:
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/pgadmin_password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
  
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./API/wwwroot:/app/wwwroot
    secrets:
      - db_password
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5184"
      DB_CONNECTION_STRING: "Host=postgres;Database=CockDB;Username_FILE=/run/secrets/db_user;Password_FILE=/run/secrets/db_password;"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5184:5184"
    networks:
      - postgres

volumes:
  postgres_data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
    
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt